# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  all:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.1'
      - run: go version
      # test
      - run: go test ./...
      # static analysis
      - run: go vet ./...
      - run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - run: staticcheck ./...
      # build
      - run: go get github.com/mitchellh/gox && go install github.com/mitchellh/gox
      - run: |
          gox -os="linux darwin" -arch="amd64 arm64" -ldflags="-X main.Version=\'$(git describe --tags)($(git rev-parse --short HEAD))\' -w -s" -output="dist/{{.OS}}_{{.Arch}}/{{.Dir}}"
          cd dist
          ls -d * | xargs -I%% tar zcf %%.tar.gz %%
      - run: find . -type f
      # release
      - name: Release
        uses: softprops/action-gh-release@v1
        # run only when tag is "v*"
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            dist/linux_amd64.tar.gz
            dist/linux_arm64.tar.gz
            dist/darwin_amd64.tar.gz
            dist/darwin_arm64.tar.gz
          draft: false
          prerelease: false
