# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.1'
      - run: go version
      # build
      - run: go get github.com/mitchellh/gox && go install github.com/mitchellh/gox
      - run: gox -os="linux darwin" -arch="amd64 arm64" -output="dist/{{.OS}}_{{.Arch}}/{{.Dir}}"
      - run: cd dist && ls -d * | xargs -I%% tar zcf %%.tar.gz %%
      - run: find . -type f
      # release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/linux_amd64.tar.gz
            dist/linux_arm64.tar.gz
            dist/darwin_amd64.tar.gz
            dist/darwin_arm64.tar.gz
